# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jruhland/SimpleAES

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jruhland/SimpleAES

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jruhland/SimpleAES/CMakeFiles /home/jruhland/SimpleAES//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jruhland/SimpleAES/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named crypter

# Build rule for target.
crypter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crypter
.PHONY : crypter

# fast build rule for target.
crypter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/build
.PHONY : crypter/fast

lib/aes.o: lib/aes.cpp.o

.PHONY : lib/aes.o

# target to build an object file
lib/aes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/lib/aes.cpp.o
.PHONY : lib/aes.cpp.o

lib/aes.i: lib/aes.cpp.i

.PHONY : lib/aes.i

# target to preprocess a source file
lib/aes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/lib/aes.cpp.i
.PHONY : lib/aes.cpp.i

lib/aes.s: lib/aes.cpp.s

.PHONY : lib/aes.s

# target to generate assembly for a file
lib/aes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/lib/aes.cpp.s
.PHONY : lib/aes.cpp.s

src/crypter.o: src/crypter.cpp.o

.PHONY : src/crypter.o

# target to build an object file
src/crypter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/src/crypter.cpp.o
.PHONY : src/crypter.cpp.o

src/crypter.i: src/crypter.cpp.i

.PHONY : src/crypter.i

# target to preprocess a source file
src/crypter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/src/crypter.cpp.i
.PHONY : src/crypter.cpp.i

src/crypter.s: src/crypter.cpp.s

.PHONY : src/crypter.s

# target to generate assembly for a file
src/crypter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/src/crypter.cpp.s
.PHONY : src/crypter.cpp.s

src/helpers.o: src/helpers.cpp.o

.PHONY : src/helpers.o

# target to build an object file
src/helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/src/helpers.cpp.o
.PHONY : src/helpers.cpp.o

src/helpers.i: src/helpers.cpp.i

.PHONY : src/helpers.i

# target to preprocess a source file
src/helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/src/helpers.cpp.i
.PHONY : src/helpers.cpp.i

src/helpers.s: src/helpers.cpp.s

.PHONY : src/helpers.s

# target to generate assembly for a file
src/helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/src/helpers.cpp.s
.PHONY : src/helpers.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

test/cbc.o: test/cbc.cpp.o

.PHONY : test/cbc.o

# target to build an object file
test/cbc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/cbc.cpp.o
.PHONY : test/cbc.cpp.o

test/cbc.i: test/cbc.cpp.i

.PHONY : test/cbc.i

# target to preprocess a source file
test/cbc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/cbc.cpp.i
.PHONY : test/cbc.cpp.i

test/cbc.s: test/cbc.cpp.s

.PHONY : test/cbc.s

# target to generate assembly for a file
test/cbc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/cbc.cpp.s
.PHONY : test/cbc.cpp.s

test/cfb.o: test/cfb.cpp.o

.PHONY : test/cfb.o

# target to build an object file
test/cfb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/cfb.cpp.o
.PHONY : test/cfb.cpp.o

test/cfb.i: test/cfb.cpp.i

.PHONY : test/cfb.i

# target to preprocess a source file
test/cfb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/cfb.cpp.i
.PHONY : test/cfb.cpp.i

test/cfb.s: test/cfb.cpp.s

.PHONY : test/cfb.s

# target to generate assembly for a file
test/cfb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/cfb.cpp.s
.PHONY : test/cfb.cpp.s

test/ecb.o: test/ecb.cpp.o

.PHONY : test/ecb.o

# target to build an object file
test/ecb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/ecb.cpp.o
.PHONY : test/ecb.cpp.o

test/ecb.i: test/ecb.cpp.i

.PHONY : test/ecb.i

# target to preprocess a source file
test/ecb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/ecb.cpp.i
.PHONY : test/ecb.cpp.i

test/ecb.s: test/ecb.cpp.s

.PHONY : test/ecb.s

# target to generate assembly for a file
test/ecb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/ecb.cpp.s
.PHONY : test/ecb.cpp.s

test/lib.o: test/lib.cpp.o

.PHONY : test/lib.o

# target to build an object file
test/lib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/lib.cpp.o
.PHONY : test/lib.cpp.o

test/lib.i: test/lib.cpp.i

.PHONY : test/lib.i

# target to preprocess a source file
test/lib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/lib.cpp.i
.PHONY : test/lib.cpp.i

test/lib.s: test/lib.cpp.s

.PHONY : test/lib.s

# target to generate assembly for a file
test/lib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/lib.cpp.s
.PHONY : test/lib.cpp.s

test/pcbc.o: test/pcbc.cpp.o

.PHONY : test/pcbc.o

# target to build an object file
test/pcbc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/pcbc.cpp.o
.PHONY : test/pcbc.cpp.o

test/pcbc.i: test/pcbc.cpp.i

.PHONY : test/pcbc.i

# target to preprocess a source file
test/pcbc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/pcbc.cpp.i
.PHONY : test/pcbc.cpp.i

test/pcbc.s: test/pcbc.cpp.s

.PHONY : test/pcbc.s

# target to generate assembly for a file
test/pcbc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/pcbc.cpp.s
.PHONY : test/pcbc.cpp.s

test/test.o: test/test.cpp.o

.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

test/utils.o: test/utils.cpp.o

.PHONY : test/utils.o

# target to build an object file
test/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/utils.cpp.o
.PHONY : test/utils.cpp.o

test/utils.i: test/utils.cpp.i

.PHONY : test/utils.i

# target to preprocess a source file
test/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/utils.cpp.i
.PHONY : test/utils.cpp.i

test/utils.s: test/utils.cpp.s

.PHONY : test/utils.s

# target to generate assembly for a file
test/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypter.dir/build.make CMakeFiles/crypter.dir/test/utils.cpp.s
.PHONY : test/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... crypter"
	@echo "... lib/aes.o"
	@echo "... lib/aes.i"
	@echo "... lib/aes.s"
	@echo "... src/crypter.o"
	@echo "... src/crypter.i"
	@echo "... src/crypter.s"
	@echo "... src/helpers.o"
	@echo "... src/helpers.i"
	@echo "... src/helpers.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... test/cbc.o"
	@echo "... test/cbc.i"
	@echo "... test/cbc.s"
	@echo "... test/cfb.o"
	@echo "... test/cfb.i"
	@echo "... test/cfb.s"
	@echo "... test/ecb.o"
	@echo "... test/ecb.i"
	@echo "... test/ecb.s"
	@echo "... test/lib.o"
	@echo "... test/lib.i"
	@echo "... test/lib.s"
	@echo "... test/pcbc.o"
	@echo "... test/pcbc.i"
	@echo "... test/pcbc.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
	@echo "... test/utils.o"
	@echo "... test/utils.i"
	@echo "... test/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

