cc_library(
  name = "crypter",
  hdrs = [
    "crypter.h"
  ],
  srcs = [
    "crypter.cpp",
    "helpers.cpp",
    "utils.cpp",
  ],
  deps = ["//lib:aes"],
  visibility = ["//visibility:public"],
)